dependencies:
- name: elasticsearch
  repository: http://helm.elastic.co 
  version: 7.5.1
  condition: "elasticsearch.enabled"
- name: kibana
  repository: http://helm.elastic.co 
  version: 7.5.1
  condition: "kibana.enabled"
- name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 8.5.11
  condition: "prometheus.enabled"
  
