# Default values 
replicaCount: 1

debug: false

image:
  repository: spvest/azure-keyvault-webhook
  tag: 0.1.0-alpha.18
  pullPolicy: IfNotPresent

envImage:
  repository: spvest/azure-keyvault-env
  tag: 0.1.0-alpha.18
  
service:
  name: azure-keyvault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 443

customAuth:
  enabled: false
  autoInject: true
  autoInjectSecretName: env-injector-secret-name
  podIdentitySelector: azure-key-vault

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

aad-pod-identity:
  enabled: false # set to true and uncomment below to install pod-identity
  # azureIdentity:
  #   type: 0 # type 0: MSI, type 1: Service Principal
  #   resourceID: "" # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  #   clientID: ""
