# Default values for spot-config-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

debug: true

image:
  repository: spvest/azure-keyvault-webhook
  tag: 0.1.0-alpha.2
  pullPolicy: IfNotPresent

service:
  name: azure-keyvault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 443

env:
  AZUREKEYVAULT_ENV_IMAGE: spvest/azure-keyvault-env:0.1.0-alpha.2
  AZURE_KEYVAULT_SECRET_NAME: azure-keyvault-credentials-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
