apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kyc-worker.fullname" . }}
  namespace: {{ include "kyc-worker.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kyc-worker.name" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.replicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 256Mi