{{- $namespace := include "kyc-worker.name" . -}}
{{- $application := include "kyc-worker.fullname" . -}}
{{- $keyvault := .Values.azure.keyvault -}}
{{- range $secret := .Values.secrets }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $application }}
  namespace: {{ $namespace }}
spec:
  vault:
    name: azure
    object:
      type: secret
      name: {{ $secret.value | quote }}
---
{{- end }}
