{{- if .Values.controller.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}-env
  labels:
    app: {{ template "akv2k8s.controller.name" . }}
    chart: {{ template "akv2k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.controller.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end}}