{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "akv2k8s.controller.name" . }}
    helm.sh/chart: {{ template "akv2k8s.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end}}