{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  labels:
    app: {{ template "akv2k8s.controller.name" . }}
    chart: {{ template "akv2k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
{{- end}}