{{- if .Values.controller.enabled -}}
{{- $dot := . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}
  labels:
    app: {{ template "akv2k8s.controller.name" . }}
    chart: {{ template "akv2k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.controller.labels }}
{{ toYaml .Values.controller.labels | indent 4 }}
{{- end}}
spec:
  selector:
    matchLabels:
      app: {{ template "akv2k8s.controller.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "akv2k8s.controller.fullname" . }}
        release: {{ .Release.Name }}
{{- if .Values.controller.podLabels }}
{{ toYaml .Values.controller.podLabels | indent 8 }}
{{- end}}
    spec:
      serviceAccountName: {{ template "controller.serviceAccountName" . }}
      containers:
      - name: {{ .Values.controller.name }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        env:
        - name: AZURE_VAULT_NORMAL_POLL_INTERVALS
          value: "{{ .Values.controller.keyVault.polling.normalInterval }}"
        - name: AZURE_VAULT_EXCEPTION_POLL_INTERVALS
          value: "{{ .Values.controller.keyVault.polling.failureInterval }}"
        - name: AZURE_VAULT_MAX_FAILURE_ATTEMPTS
          value: "{{ .Values.controller.keyVault.polling.failureAttempts }}"
        - name: AAD_POD_BINDING_LABEL
          valueFrom:
            fieldRef:
              fieldPath:  metadata.labels['aadpodidbinding']
        - name: RUNNING_INSIDE_AZURE_AKS
          value: {{ .Values.runningInsideAzureAks | quote }}
        - name: CUSTOM_AUTH
          value: {{ .Values.controller.customAuth | quote }}
        - name: LOG_LEVEL
          value: "{{ .Values.controller.logLevel }}"
        - name: LOG_FORMAT
          value: "{{ .Values.controller.logFormat }}"
        {{- range $key, $value := .Values.controller.env }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ template "akv2k8s.controller.fullname" $dot }}-env
              key: {{ $key }}
        {{- end }}
    {{- if not .Values.controller.keyVault.customAuth }}
        args:
          - "--cloudconfig={{ .Values.controller.cloudConfig }}"
        volumeMounts:
          - name: azure-config
            mountPath: "{{ .Values.controller.cloudConfig }}"
            readOnly: true
      volumes:
      - name: azure-config
        hostPath:
          path: "{{ .Values.controller.cloudConfig }}"
          type: File
      {{- end }}
      {{- if .Values.controller.image.pullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.controller.image.pullSecret }}"
      {{- end }}
{{- end }}