{{- if .Values.rbac.create -}}
# Cluster Role giving full access to read and create AzureKeyVaultSecrets and Secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
# CA Bundle
{{- if and .Values.env_injector.enabled .Values.keyVault.useAuthService }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
{{- end }}

---

# Cluster Role giving read access to AzureKeyVaultSecrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}-reader
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
---

# Bind ServiceAccount to Clust Role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "akv2k8s.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "akv2k8s.controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---

# Bind all ServiceAccounts in cluster to read role for AzureKeyVaultSecrets
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}-reader
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ template "akv2k8s.controller.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io

{{- if and .Values.env_injector.enabled .Values.keyVault.useAuthService }}
---
# Role giving access to local secret containing CA Bundle for akv2k8s and write access to Events
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list

---
# Link controller ServiceAccount to Role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "akv2k8s.controller.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "akv2k8s.controller.fullname" . }}-ca-bundle
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- end}}
