{{- if .Values.keyVault.env -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "akv2k8s.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ template "akv2k8s.name" . }}
    helm.sh/chart: {{ template "akv2k8s.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.keyVault.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end}}