apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "azure-key-vault-to-kubernetes.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "azure-key-vault-to-kubernetes.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webhook-apiservice.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: File
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
          # securityContext:
          #   privileged: true
          #   seLinuxOptions:
          #     type: docker_t
          env:
          - name: TLS_CERT_FILE
            value: /var/serving-cert/servingCert
          - name: TLS_PRIVATE_KEY_FILE
            value: /var/serving-cert/servingKey
          - name: DEBUG
            value: {{ .Values.webhook.debug | quote }}
          - name: AAD_POD_BINDING_LABEL
            valueFrom:
              fieldRef:
                fieldPath:  metadata.labels['aadpodidbinding']
          {{- range $key, $value := .Values.webhook.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webhook.service.internalPort }}
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
          - mountPath: "/var/run/docker.sock"
            name: dockersock
            readOnly: true
          resources:
{{ toYaml .Values.webhook.resources | indent 12 }}
    {{- if .Values.webhook.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.webhook.nodeSelector | indent 8 }}
    {{- end }}
  {{- if .Values.webhook.tolerations }}
      tolerations:
{{ toYaml .Values.webhook.tolerations | indent 8 }}
  {{- end }}
  {{- if .Values.webhook.affinity }}
      affinity:
{{ toYaml .Values.webhook.affinity | indent 8 }}
  {{- end }}
