name: build and publish

on:
  push:
    branches:
    - master
    paths:
    - 'stable/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Publish
      run: cat publish.sh | sh

    - name: Verify
      run: |
        alias helm=/tmp/helm/bin/linux-amd64/helm
        if [ "$CIRCLE_BRANCH" = "master" ]; then
          helm repo add spv-charts https://charts.spvapi.no
          helm repo update
          helm repo list
          helm inspect spv-charts/azure-key-vault-controller --version 0.1.0-alpha.2
        fi