name: build and publish

on:
  push:
    branches:
    - master

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Publish
      env:
        GITHUB_PAGES_REPO: sparebankenvest/helm-charts
        CUSTOM_DOMAIN: charts.spvapi.no
        GITHUB_PAGES_BRANCH: gh-pages
        HELM_VERSION: 2.12.2
      run: ./publish.sh

    - name: Verify
      run: |
        alias helm=/tmp/helm/bin/linux-amd64/helm
        if [ "$CIRCLE_BRANCH" = "master" ]; then
          helm repo add spv-charts https://charts.spvapi.no
          helm repo update
          helm repo list
          helm inspect spv-charts/azure-key-vault-controller --version 0.1.0-alpha.2
        fi